version: "3.8"

services:
  pokemon-quiz-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings:Redis=redis:6379
      - Sentry:Dsn=
      - Sentry:Debug=false
      - Sentry:TracesSampleRate=0.5
      - Sentry:ProfilesSampleRate=1
    depends_on:
      - redis
  redis:
    image: "redis:alpine"