version: "3.8"

services:
  pokemon-quiz-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings:Redis=${REDIS_CONNECTION_STRING}
      - Sentry:Dsn=${SENTRY_DSN}
      - Sentry:Debug=false
      - Sentry:TracesSampleRate=0.5
      - Sentry:ProfilesSampleRate=1
    depends_on:
      - redis
  redis:
    image: "redis:alpine"