services:
  pokemon-quiz-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"