version: "3.8"

services:
  pokemon-quiz-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - Sentry:Debug=false
      - Sentry:TracesSampleRate=0.5
      - Sentry:ProfilesSampleRate=1
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"