version: "3.8"

services:
  pokemon-quiz-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=
      - ConnectionStrings__Redis=
      - Sentry__Dsn=
      - Sentry__Debug=false
      - Sentry__TracesSampleRate=0.5
      - Sentry__ProfilesSampleRate=1
    depends_on:
      - redis
  redis:
    image: "redis:alpine"