name: build and publish

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      artifactName:
        description: 'Name of the artifact generated'
        type: string
        required: true

jobs:
  
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    
    env:
      Sentry:Dsn: ${{ secrets.SENTRY_DSN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release

    - name: Execute unit tests
      run: dotnet test --collect:"Code Coverage;Format=Xml;CoverageFileName=coverage.xml" --results-directory ./coverage
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./src
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        