on:
  pull_request:
  push:
    
jobs:
  build:
    permissions: write-all
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  deploy-dev:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions: write-all
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: development
  
  deploy-prod:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions: write-all
    needs: deploy-dev
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production