name: run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: github-runner-y69hOM3Mf3eYk
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # Install the .NET Core workload
    - name: Install dependencies
      run: dotnet restore
    
    # Build the solution
    - name: Build
      run: dotnet build

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
